version: "2"

build:
  os: "ubuntu-22.04"
  image: latest
  tools:
    python: "3.10"
  pre:
    - pip install -r docs/requirements.txt
    - sphinx-apidoc -o docs/source ./setminga

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

